import type { CardTemplate } from '../../types'

const handwritingChoices = [
  'Gaegu',
  'Patrick Hand',
  'Gochi Hand',
  'Schoolbell',
  'Short Stack',
]

const template: CardTemplate = {
  id: 'tyler-call-me-if-you-get-lost',
  title: 'call me if you get lost license',
  caption: 'tyler: call me if you get lost license',
  orientation: 'landscape',
  sizeMm: { width: 85.6, height: 54 },
  previewImage: '/templates/tylerthecreator/callmeifyougetlostid.png',
  front: {
    backgroundImage: '/templates/tylerthecreator/callmeifyougetlostid.png',
    fields: [
      {
        id: 'photo',
        type: 'photo',
        x: 8.3,
        y: 16.2,
        width: 38.4,
        height: 66.2,
      },
      {
        id: 'number',
        type: 'text',
        x: 59.5,
        y: 17,
        width: 30,
        height: 4.5,
        font: 'Special Elite',
        size: 16,
        color: '#1a1a1a',
        alignment: 'center',
        backgroundColor: '#f4e8c4',
        autoFit: true,
        valuePrefix: 'NO. ',
        maxLength: 14,
      },
      {
        id: 'name',
        type: 'text',
        x: 61.5,
        y: 22.8,
        width: 29.2,
        height: 3.6,
        fontValue: 'handwritingStyle',
        size: 19,
        color: '#1a1a1a',
        autoFit: true,
        maxLength: 32,
        placeholder: 'name',
      },
      {
        id: 'birthDate',
        type: 'text',
        x: 61.5,
        y: 28.9,
        width: 29.2,
        height: 3.5,
        fontValue: 'handwritingStyle',
        size: 18,
        color: '#1a1a1a',
        autoFit: true,
        dateFormat: 'mm/dd/yyyy',
      },
      {
        id: 'placeOfIssue',
        type: 'text',
        x: 61.5,
        y: 35.2,
        width: 29.2,
        height: 3.5,
        fontValue: 'handwritingStyle',
        size: 18,
        color: '#1a1a1a',
        autoFit: true,
        maxLength: 32,
      },
      {
        id: 'signature',
        type: 'image',
        x: 58,
        y: 83,
        width: 33,
        height: 5.2,
        imageFit: 'contain',
        imageAlign: 'center',
      },
    ],
  },
  back: {
    backgroundImage: '/templates/tylerthecreator/back.svg',
    fields: [
      {
        id: 'phoneNumber',
        type: 'text',
        x: 23,
        y: 51,
        width: 53,
        height: 8,
        font: 'Special Elite',
        size: 21,
        color: '#1a1a1a',
        alignment: 'center',
        autoFit: true,
        visibleWhen: { field: 'backMode', value: 'phone' },
        maxLength: 24,
      },
      {
        id: 'custom-qr',
        type: 'qr',
        x: 75,
        y: 34.5,
        width: 15.5,
        height: 24.6,
        imageFit: 'contain',
        visibleWhen: { field: 'backMode', value: 'qr' },
      },
      {
        id: 'returnAddress',
        type: 'text',
        x: 21,
        y: 74,
        width: 60,
        height: 8,
        fontValue: 'handwritingStyle',
        size: 19,
        color: '#1a1a1a',
        alignment: 'center',
        autoFit: true,
        maxLength: 64,
      },
    ],
  },
  options: [
    {
      type: 'photo',
      id: 'photo',
      label: 'photo',
    },
    {
      type: 'toggle',
      id: 'vintageFilter',
      label: 'photo filter',
      defaultValue: 'off',
      choices: [
        { label: 'original', value: 'off' },
        { label: 'vintage filter', value: 'on' },
      ],
    },
    {
      type: 'randomizeText',
      id: 'number',
      label: 'license number',
      defaultValue: 'TTC6252021',
      maxLength: 14,
    },
    {
      type: 'text',
      id: 'name',
      label: 'name',
      defaultValue: '',
      maxLength: 32,
      placeholder: 'name as it appears on the license',
    },
    {
      type: 'date',
      id: 'birthDate',
      label: 'date of birth',
    },
    {
      type: 'text',
      id: 'placeOfIssue',
      label: 'place of issue',
      defaultValue: '',
      maxLength: 32,
      placeholder: 'city, state',
    },
    {
      type: 'select',
      id: 'handwritingStyle',
      label: 'handwriting style',
      defaultValue: 'Gaegu',
      choices: handwritingChoices,
    },
    {
      type: 'signature',
      id: 'signature',
      label: 'signature',
    },
    {
      type: 'toggle',
      id: 'backMode',
      label: 'back details',
      defaultValue: 'phone',
      choices: [
        { label: 'phone number', value: 'phone' },
        { label: 'custom qr', value: 'qr' },
      ],
    },
    {
      type: 'text',
      id: 'phoneNumber',
      label: 'phone number',
      defaultValue: '',
      maxLength: 24,
      placeholder: '(555) 123-4567',
      inputType: 'tel',
    },
    {
      type: 'text',
      id: 'qrUrl',
      label: 'qr code url',
      defaultValue: '',
      maxLength: 500,
      placeholder: 'https://example.com',
    },
    {
      type: 'text',
      id: 'returnAddress',
      label: 'return address',
      defaultValue: '',
      maxLength: 64,
      placeholder: 'address to return the card',
    },
  ],
}

export default template
