import type { CardTemplate } from '../../types'
import './template.css'

const jobTitles = [
  'Regional Manager',
  'Assistant to the Regional Manager',
  'Assistant Regional Manager',
  'Salesman',
  'Receptionist',
  'Accountant',
  'HR Representative',
  'Customer Service Rep',
  'Quality Assurance',
  'Supplier Relations',
  'Warehouse Foreman',
  'Office Administrator',
  'Temp',
  'custom',
]

const template: CardTemplate = {
  id: 'dunder-mifflin',
  title: 'dunder mifflin employee id',
  caption: 'the office: dunder mifflin id',
  orientation: 'landscape',
  sizeMm: { width: 85.6, height: 54 },
  previewImage: '/templates/dundermifflin/front.jpg',
  front: {
    backgroundImage: '/templates/dundermifflin/front.jpg',
    fields: [
      {
        id: 'photoHeaderMask',
        type: 'text',
        x: 58.1,
        y: 13.2,
        width: 30.6,
        height: 29.3,
        backgroundColor: '#455468',
        defaultValue: ' ',
      },
      {
        id: 'bodyMask',
        type: 'text',
        x: 2,
        y: 41.5,
        width: 96,
        height: 55.4,
        backgroundColor: '#e7e5e6',
        defaultValue: ' ',
      },
      {
        id: 'photo',
        type: 'photo',
        x: 58.4,
        y: 13.5,
        width: 32.2,
        height: 68,
        hideIfPhotoMissing: true,
        placeholder: 'click or drop your photo',
      },
      {
        id: 'name',
        type: 'text',
        x: 5,
        y: 51,
        width: 50,
        height: 11,
        font: '"Dunder Arimo Bold", sans-serif',
        size: 25,
        color: '#111',
        alignment: 'center',
        autoFit: true,
        placeholder: 'your name',
        maxLength: 32,
      },
      {
        id: 'jobTitle',
        type: 'text',
        x: 5,
        y: 63,
        width: 50,
        height: 20,
        font: '"Dunder Arimo Regular", sans-serif',
        size: 18,
        color: '#111',
        alignment: 'center',
        autoFit: true,
        textLayout: 'assistantToRegionalManager',
        visibleWhen: {
          field: 'jobTitle',
          values: jobTitles.filter((title) => title !== 'custom'),
        },
      },
      {
        id: 'customJobTitle',
        type: 'text',
        x: 5,
        y: 63,
        width: 50,
        height: 20,
        font: '"Dunder Arimo Regular", sans-serif',
        size: 18,
        color: '#111',
        alignment: 'center',
        autoFit: true,
        visibleWhen: { field: 'jobTitle', value: 'custom' },
      },
      {
        id: 'location',
        type: 'text',
        x: 5,
        y: 86,
        width: 50,
        height: 8,
        font: '"Dunder Arimo Regular", sans-serif',
        size: 14,
        color: '#111',
        alignment: 'center',
        autoFit: true,
        maxLength: 32,
      },
      {
        id: 'employeeId',
        type: 'barcode',
        x: 58.4,
        y: 84.5,
        width: 30,
        height: 8,
      },
    ],
  },
  back: {
    backgroundImage: '/templates/dundermifflin/back.svg',
    fields: [
      {
        id: 'qrCode',
        type: 'qr',
        x: 35,
        y: 18,
        width: 30,
        height: 54,
        imageFit: 'contain',
      },
      {
        id: 'returnText',
        type: 'text',
        x: 8,
        y: 80,
        width: 84,
        height: 10,
        font: 'Arial, sans-serif',
        size: 9,
        color: '#333',
        alignment: 'center',
        autoFit: true,
        maxLength: 100,
      },
    ],
  },
  options: [
    { type: 'photo', id: 'photo', label: 'photo' },
    {
      type: 'text',
      id: 'name',
      label: 'name',
      defaultValue: '',
      maxLength: 32,
      placeholder: 'employee name',
    },
    {
      type: 'select',
      id: 'jobTitle',
      label: 'job title',
      defaultValue: 'Regional Manager',
      choices: jobTitles,
    },
    {
      type: 'text',
      id: 'customJobTitle',
      label: 'custom job title',
      defaultValue: '',
      maxLength: 32,
      placeholder: 'enter a job title',
      visibleWhen: { field: 'jobTitle', value: 'custom' },
    },
    {
      type: 'text',
      id: 'location',
      label: 'location',
      defaultValue: 'Scranton, PA',
      maxLength: 32,
    },
    {
      type: 'randomizeText',
      id: 'employeeId',
      label: 'employee ID',
      defaultValue: 'DMI-0041827',
      maxLength: 12,
      prefix: 'DMI-',
    },
    {
      type: 'text',
      id: 'qrUrl',
      label: 'QR code URL or text',
      defaultValue: 'https://dundermifflin.com',
      maxLength: 500,
      placeholder: 'URL or text to encode',
    },
    {
      type: 'text',
      id: 'returnText',
      label: 'return text',
      defaultValue: 'if found, return to dunder mifflin paper company, scranton, pa',
      maxLength: 100,
    },
  ],
}

export default template
