import type { CardTemplate } from '../../types'

const template: CardTemplate = {
  id: 'oscorp',
  title: 'oscorp staff id',
  caption: 'tasm: oscorp staff id',
  orientation: 'portrait',
  sizeMm: { width: 85.6, height: 54 },
  previewImage: '/templates/oscorp/front-background.svg',
  front: {
    backgroundImage: '/templates/oscorp/front-background.svg',
    fields: [
      {
        id: 'company',
        type: 'text',
        x: 13,
        y: 5.2,
        width: 74,
        height: 5.5,
        font: 'Arial, sans-serif',
        size: 13,
        color: '#111111',
        alignment: 'center',
        defaultValue: 'OSCORP INDUSTRIES',
      },
      {
        id: 'staff-label',
        type: 'text',
        x: 3.2,
        y: 28,
        width: 6,
        height: 35,
        font: 'Arial, sans-serif',
        size: 11,
        color: '#111111',
        alignment: 'center',
        writingMode: 'vertical-rl',
        defaultValue: 'STAFF',
      },
      {
        id: 'photo',
        type: 'photo',
        x: 18,
        y: 15,
        width: 64,
        height: 48,
      },
      {
        id: 'employeeNumber',
        type: 'text',
        x: 90.5,
        y: 17,
        width: 6,
        height: 46,
        font: 'Arial, sans-serif',
        size: 10,
        color: '#111111',
        alignment: 'center',
        writingMode: 'vertical-rl',
        maxLength: 12,
      },
      {
        id: 'name',
        type: 'text',
        x: 17,
        y: 68,
        width: 66,
        height: 8,
        font: 'Arial, sans-serif',
        size: 13,
        color: '#111111',
        alignment: 'center',
        maxLength: 28,
        placeholder: 'your name',
      },
      {
        id: 'department',
        type: 'text',
        x: 12,
        y: 84,
        width: 76,
        height: 7,
        font: 'Arial, sans-serif',
        size: 9,
        color: '#111111',
        alignment: 'center',
        maxLength: 32,
      },
    ],
  },
  back: {
    backgroundImage: '/templates/oscorp/back-background.svg',
    fields: [
      {
        id: 'magnetic-stripe',
        type: 'image',
        x: 7,
        y: 13,
        width: 12,
        height: 74,
        defaultValue: '/templates/oscorp/magnetic-stripe.svg',
      },
      {
        id: 'oscorp-logo',
        type: 'image',
        x: 70,
        y: 72,
        width: 21,
        height: 18,
        defaultValue: '/templates/oscorp/oscorp-logo.svg',
        visibleWhen: { field: 'backMode', value: 'logo' },
      },
      {
        id: 'custom-qr',
        type: 'qr',
        x: 68,
        y: 66,
        width: 25,
        height: 25,
        visibleWhen: { field: 'backMode', value: 'qr' },
      },
    ],
  },
  options: [
    {
      type: 'text',
      id: 'name',
      label: 'name',
      defaultValue: 'PETER PARKER',
      maxLength: 28,
      placeholder: 'your name',
    },
    {
      type: 'text',
      id: 'employeeNumber',
      label: 'employee number',
      defaultValue: 'A00473',
      maxLength: 12,
    },
    {
      type: 'select',
      id: 'department',
      label: 'department',
      defaultValue: 'GENETICS LABORATORY',
      choices: [
        'GENETICS LABORATORY',
        'CROSS-SPECIES',
        'BIOPHYSICS',
        'EXECUTIVE',
        'SECURITY',
      ],
    },
    {
      type: 'toggle',
      id: 'backMode',
      label: 'back side',
      defaultValue: 'logo',
      choices: [
        { label: 'oscorp logo', value: 'logo' },
        { label: 'custom qr', value: 'qr' },
      ],
    },
    {
      type: 'text',
      id: 'qrUrl',
      label: 'qr code url',
      defaultValue: 'https://example.com',
      maxLength: 500,
      placeholder: 'https://example.com',
    },
    { type: 'photo', id: 'photo', label: 'photo' },
  ],
}

export default template
