import type { CardTemplate } from '../../types'

const template: CardTemplate = {
  id: 'oscorp',
  title: 'oscorp staff id',
  caption: 'tasm: oscorp staff id',
  orientation: 'portrait',
  sizeMm: { width: 85.6, height: 54 },
  previewImage: '/templates/oscorp/oscorp_front.png',
  front: {
    backgroundImage: '/templates/oscorp/oscorp_front.png',
    fields: [
      {
        id: 'photo',
        type: 'photo',
        x: 25.5,
        y: 38,
        width: 51.5,
        height: 37.8,
      },
      {
        id: 'employeeNumber',
        type: 'text',
        x: 83,
        y: 46,
        width: 8,
        height: 25,
        font: 'Arial, sans-serif',
        size: 13,
        color: '#111111',
        alignment: 'center',
        writingMode: 'vertical-rl',
        backgroundColor: '#ffffff',
        maxLength: 12,
      },
      {
        id: 'name',
        type: 'text',
        x: 15,
        y: 78.5,
        width: 70,
        height: 5,
        font: 'Arial, sans-serif',
        size: 14,
        color: '#111111',
        alignment: 'center',
        backgroundColor: '#ffffff',
        maxLength: 28,
        placeholder: 'your name',
      },
      {
        id: 'department',
        type: 'text',
        x: 15,
        y: 85.5,
        width: 70,
        height: 4,
        font: 'Arial, sans-serif',
        size: 11,
        color: '#111111',
        alignment: 'center',
        backgroundColor: '#ffffff',
        maxLength: 32,
      },
    ],
  },
  back: {
    backgroundImage: '/templates/oscorp/oscorp_back.svg',
    fields: [
      {
        id: 'oscorp-logo',
        type: 'image',
        x: 42,
        y: 76,
        width: 50,
        height: 15,
        defaultValue: '/templates/oscorp/oscorp%20logo.svg',
        imageFit: 'contain',
        imageAlign: 'right',
        backgroundColor: '#ffffff',
        visibleWhen: { field: 'backMode', value: 'logo' },
      },
      {
        id: 'custom-qr',
        type: 'qr',
        x: 42,
        y: 76,
        width: 50,
        height: 15,
        imageFit: 'contain',
        imageAlign: 'right',
        backgroundColor: '#ffffff',
        visibleWhen: { field: 'backMode', value: 'qr' },
      },
    ],
  },
  options: [
    {
      type: 'text',
      id: 'name',
      label: 'name',
      defaultValue: 'PETER PARKER',
      maxLength: 28,
      placeholder: 'your name',
    },
    {
      type: 'text',
      id: 'employeeNumber',
      label: 'employee number',
      defaultValue: 'A00473',
      maxLength: 12,
    },
    {
      type: 'select',
      id: 'department',
      label: 'department',
      defaultValue: 'GENETICS LABORATORY',
      choices: [
        'GENETICS LABORATORY',
        'CROSS-SPECIES',
        'BIOPHYSICS',
        'EXECUTIVE',
        'SECURITY',
      ],
    },
    {
      type: 'toggle',
      id: 'backMode',
      label: 'back side',
      defaultValue: 'logo',
      choices: [
        { label: 'oscorp logo', value: 'logo' },
        { label: 'custom qr', value: 'qr' },
      ],
    },
    {
      type: 'text',
      id: 'qrUrl',
      label: 'qr code url',
      defaultValue: 'https://example.com',
      maxLength: 500,
      placeholder: 'https://example.com',
    },
    { type: 'photo', id: 'photo', label: 'photo' },
  ],
}

export default template
